blank_issues_enabled: false
contact_links:
  - name: Development Help
    about: Help on the Development
    url: https://github.com/YouTube-Remote-Upload/Web_Extension/discussions
  - name: Usage Help
    about: Help on the Usage
    url: https://github.com/YouTube-Remote-Upload/Web_Extension/discussions
